<script setup lang="ts">
import { ref } from 'vue'

import HomeScreen from '@/components/testing-screens/HomeScreen.vue'
import FormScreen from '@/components/testing-screens/FormScreen.vue'
import BurbonTest from '@/components/BurbonTest.vue'
import ResultScreen from '@/components/testing-screens/ResultScreen.vue'
import { TIME_FOR_TEST } from '@/script/constants'

const screen = ref(0)

const changeScreen = (screenValue: number) => {
  if (screenValue !== undefined) screen.value = screenValue
  else screen.value++
}

const bourdonTestStrings = [
  {
    strings: [
      // Строка 1
      { letter: 'к', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 2
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'в', isCorrect: false },
      // Строка 3
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 4
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 5
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 6
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'р', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 7
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'к', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      // Строка 8
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      // Строка 9
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'б', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      // Строка 10
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
    ],
    gridColumns: 10,
    initialTime: TIME_FOR_TEST,
    screen: 2,
  },
  {
    strings: [
      // Строка 1
      { letter: 'к', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 2
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'в', isCorrect: false },
      // Строка 3
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 4
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 5
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 6
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'р', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 7
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'к', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      // Строка 8
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      // Строка 9
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'б', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      // Строка 10
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
    ],
    gridColumns: 10,
    initialTime: TIME_FOR_TEST,
    screen: 3,
  },
  {
    strings: [
      // Строка 1
      { letter: 'к', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 2
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'в', isCorrect: false },
      // Строка 3
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 4
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      // Строка 5
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 6
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'р', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      // Строка 7
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'к', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'е', isCorrect: false },
      // Строка 8
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      // Строка 9
      { letter: 'в', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'а', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'б', isCorrect: false },
      { letter: 'е', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      // Строка 10
      { letter: 'д', isCorrect: true },
      { letter: 'е', isCorrect: false },
      { letter: 'б', isCorrect: false },
      { letter: 'р', isCorrect: false },
      { letter: 'в', isCorrect: false },
      { letter: 'д', isCorrect: true },
      { letter: 'а', isCorrect: false },
      { letter: 'г', isCorrect: false },
      { letter: 'к', isCorrect: false },
      { letter: 'д', isCorrect: true },
    ],
    gridColumns: 10,
    initialTime: TIME_FOR_TEST,
    screen: 4,
  },
]
</script>

<template>
  <div>
    <HomeScreen v-if="screen === 0" @change-screen="changeScreen" />
    <FormScreen v-else-if="screen === 1" @change-screen="changeScreen" />
    <div v-for="(bourdonString, index) in bourdonTestStrings" :key="bourdonString.screen">
      <BurbonTest
        v-if="screen === bourdonString.screen"
        @change-screen="changeScreen"
        :burbon-strings="bourdonString.strings"
        :grid-columns="bourdonString.gridColumns"
        :initial-time="bourdonString.initialTime"
        :test-number="index + 1"
      />
    </div>
    <ResultScreen v-if="screen === 5" @change-screen="changeScreen(1)" />
  </div>
</template>

<style scoped></style>
